# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed442af678505c5e54f99e13327b5932960ddc01a118fd58283ba44a8dfd3be95b7441c4eb506cde575bfcfc5622f4567f1224801bd4b558c0bafc59227102cc

test:
  secret_key_base: 880760ac1e5b9b3bdfa87f6dda55f4b9441d219afa0b0bffd190bf0c14e98cbcc89c283e1b65b32f58c2de2c8de164623bc300b5c3d1a90c674eb4a6877bb6e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
